<?php
/**
 * A drop-in published by an older release must not fatal after an update.
 *
 * @package GTPerformance
 */

declare(strict_types=1);

namespace GTPerformance\Tests\Unit;

use PHPUnit\Framework\TestCase;

/**
 * advanced-cache.php runs from wp-settings.php, before WordPress exists. A fatal
 * raised there takes the front end and wp-admin down together, and the only way
 * back is filesystem access. The drop-in published up to 1.0.0 hard-codes the
 * list of runtime files it loads, so every later release must stay loadable
 * from that exact list until the drop-in is replaced.
 */
final class LegacyDropinCompatibilityTest extends TestCase {
	/**
	 * The file list baked into drop-ins published up to 1.0.0.
	 *
	 * @return list<string>
	 */
	private static function legacyRuntimeFiles(): array {
		return array(
			'Decision.php',
			'RequestContext.php',
			'Eligibility.php',
			'CacheKey.php',
			'DropinRuntime.php',
		);
	}

	/**
	 * Run serve() in a separate process loaded ONLY from the legacy file list,
	 * with no autoloader, exactly as an old drop-in would.
	 */
	private function serveFromLegacyDropin( string $configContents ): string {
		$temp   = sys_get_temp_dir() . '/gtperf-legacy-' . bin2hex( random_bytes( 6 ) );
		mkdir( $temp, 0o777, true );
		$config = $temp . '/config.php';

		if ( '' !== $configContents ) {
			file_put_contents( $config, $configContents );
		}

		$source = GTPERF_DIR . '/src/Cache';
		$loads  = '';
		foreach ( self::legacyRuntimeFiles() as $file ) {
			$loads .= 'require_once ' . var_export( $source . '/' . $file, true ) . ";\n";
		}

		$script = "<?php\n"
			. "define( 'ABSPATH', " . var_export( $temp . '/', true ) . " );\n"
			. $loads
			. "\$_SERVER['REQUEST_METHOD'] = 'GET';\n"
			. "\$_SERVER['HTTP_HOST'] = 'example.com';\n"
			. "\$_SERVER['REQUEST_URI'] = '/';\n"
			. '\\GTPerformance\\Cache\\DropinRuntime::serve( ' . var_export( $config, true ) . ', ' . var_export( $temp . '/pages', true ) . " );\n"
			. "echo 'OK';\n";

		$runner = $temp . '/runner.php';
		file_put_contents( $runner, $script );

		$output = shell_exec( escapeshellarg( PHP_BINARY ) . ' -d display_errors=1 ' . escapeshellarg( $runner ) . ' 2>&1' );

		array_map( 'unlink', glob( $temp . '/*' ) ?: array() );
		rmdir( $temp );

		return (string) $output;
	}

	public function test_legacy_dropin_survives_a_legacy_format_configuration(): void {
		$output = $this->serveFromLegacyDropin(
			"<?php\n// Generated by GT Performance. Do not edit.\ndefined( 'ABSPATH' ) || exit;\nreturn array( 'cache' => array( 'enabled' => true ) );\n"
		);

		self::assertStringNotContainsString( 'Fatal error', $output );
		self::assertStringNotContainsString( 'not found', $output );
		self::assertStringEndsWith( 'OK', trim( $output ) );
	}

	public function test_legacy_dropin_survives_a_deleted_configuration(): void {
		$output = $this->serveFromLegacyDropin( '' );

		self::assertStringNotContainsString( 'Fatal error', $output );
		self::assertStringEndsWith( 'OK', trim( $output ) );
	}

	/**
	 * The guarded 1.0.1 file must never sit at the legacy path, but if one ever
	 * did, reading it must still not execute it.
	 */
	public function test_legacy_dropin_survives_a_guarded_configuration(): void {
		$output = $this->serveFromLegacyDropin(
			"<?php exit; /* GT Performance data file. Not executable configuration. */ ?>\n" . json_encode( array( 'cache' => array( 'enabled' => true ) ) )
		);

		self::assertStringNotContainsString( 'Fatal error', $output );
		self::assertStringEndsWith( 'OK', trim( $output ) );
	}
}
