<?php
/**
 * Store-build migration tests.
 *
 * @package GTPerformance
 */

declare(strict_types=1);

namespace GTPerformance\Tests\Unit;

use GTPerformance\Core\Paths;
use GTPerformance\Migration\Migrator;
use PHPUnit\Framework\TestCase;

final class MigratorTest extends TestCase {
	protected function setUp(): void {
		$GLOBALS['gtperf_test_options'] = array();

		foreach ( Paths::writableDirectories() as $directory ) {
			is_dir( $directory ) || mkdir( $directory, 0o777, true );
		}

		is_dir( ABSPATH ) || mkdir( ABSPATH, 0o777, true );
		file_put_contents( ABSPATH . 'wp-config.php', "<?php\n/* Test config. */\n" );
	}

	protected function tearDown(): void {
		foreach ( array( 'config.php', 'redis-config.php' ) as $name ) {
			$path = Paths::cacheRoot() . '/' . $name;
			is_file( $path ) && unlink( $path );
		}
		is_file( ABSPATH . 'wp-config.php' ) && unlink( ABSPATH . 'wp-config.php' );
		$target = WP_CONTENT_DIR . '/advanced-cache.php';
		is_file( $target ) && unlink( $target );
	}

	private function writeLegacyConfig(): void {
		foreach ( array( 'config.php', 'redis-config.php' ) as $name ) {
			file_put_contents(
				Paths::cacheRoot() . '/' . $name,
				"<?php\n// Generated by GT Performance. Do not edit.\nreturn array();\n"
			);
		}
	}

	public function test_removes_configuration_files_written_before_1_0_1(): void {
		$this->writeLegacyConfig();

		( new Migrator() )->run();

		foreach ( array( 'config.php', 'redis-config.php' ) as $name ) {
			self::assertFileDoesNotExist(
				Paths::cacheRoot() . '/' . $name,
				"{$name} is read with require by a pre-1.0.1 drop-in and must not survive migration."
			);
		}
	}

	public function test_leaves_the_current_configuration_in_place(): void {
		( new Migrator() )->run();

		self::assertFileExists( Paths::config() );
		self::assertStringEndsWith( '.json.php', Paths::config() );
	}

	public function test_removes_transients_written_before_the_rename(): void {
		set_transient( 'gtp_warm_pending', 1, 300 );
		set_transient( 'gtp_revalidate_pending', 1, 300 );

		( new Migrator() )->run();

		self::assertFalse( get_transient( 'gtp_warm_pending' ) );
		self::assertFalse( get_transient( 'gtp_revalidate_pending' ) );
	}

	public function test_records_the_version_it_migrated_to(): void {
		( new Migrator() )->run();

		self::assertSame( GTPERF_VERSION, $GLOBALS['gtperf_test_options']['gt_performance_migrated_version'] ?? null );
	}

	public function test_running_twice_is_safe(): void {
		$this->writeLegacyConfig();

		$migrator = new Migrator();
		$migrator->run();
		$migrator->run();

		self::assertFileExists( Paths::config() );
		self::assertFileDoesNotExist( Paths::cacheRoot() . '/config.php' );
	}

	/**
	 * The upgrader hook must only fire for this plugin. Reacting to another
	 * plugin's update would republish drop-ins at an arbitrary moment.
	 */
	public function test_upgrade_hook_ignores_other_plugins(): void {
		$this->writeLegacyConfig();

		( new Migrator() )->afterUpgrade( null, array( 'type' => 'plugin', 'plugins' => array( 'some-other/plugin.php' ) ) );

		self::assertFileExists(
			Paths::cacheRoot() . '/config.php',
			'Migration ran for an unrelated plugin update.'
		);
	}

	public function test_upgrade_hook_runs_for_this_plugin(): void {
		$this->writeLegacyConfig();

		( new Migrator() )->afterUpgrade( null, array( 'type' => 'plugin', 'plugins' => array( GTPERF_BASENAME ) ) );

		self::assertFileDoesNotExist( Paths::cacheRoot() . '/config.php' );
	}

	public function test_upgrade_hook_ignores_theme_updates(): void {
		$this->writeLegacyConfig();

		( new Migrator() )->afterUpgrade( null, array( 'type' => 'theme', 'themes' => array( 'twentytwentyfive' ) ) );

		self::assertFileExists( Paths::cacheRoot() . '/config.php' );
	}
}
